"use client";

import { useEffect, useState, useMemo } from "react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import SpendingChart from "@/components/SpendingChart";
import { ToolItem, Currency } from "@/lib/types";
import { calculateAudit } from "@/lib/auditLogic";
import { Plus, Trash2, Download, AlertCircle, CheckCircle, TrendingUp } from "lucide-react";

const POPULAR_TOOLS = [
  "ChatGPT",
  "Claude",
  "Cursor",
  "GitHub Copilot",
  "Google Gemini",
  "Midjourney",
  "Perplexity",
  "Custom Tool",
];

export default function AuditPage() {
  const [currency, setCurrency] = useState<Currency>("$");
  const [tools, setTools] = useState<ToolItem[]>([
    {
      id: "tool-1",
      name: "ChatGPT",
      spend: 40,
      teamSize: 1,
    },
    {
      id: "tool-2",
      name: "Cursor",
      spend: 20,
      teamSize: 1,
    },
  ]);

  // Load from localStorage on initial render
  useEffect(() => {
    const savedTools = localStorage.getItem("my_tools");
    const savedCurrency = localStorage.getItem("my_currency");

    if (savedTools) {
      try {
        const parsed = JSON.parse(savedTools);
        if (Array.isArray(parsed) && parsed.length > 0) {
          setTools(parsed);
        }
      } catch (err) {
        console.error("Error reading localStorage", err);
      }
    }

    if (savedCurrency) {
      setCurrency(savedCurrency as Currency);
    }
  }, []);

  // Save to localStorage whenever state changes
  useEffect(() => {
    localStorage.setItem("my_tools", JSON.stringify(tools));
    localStorage.setItem("my_currency", currency);
  }, [tools, currency]);

  // Calculations using our helper function
  const { totalSpend, totalSavings, yearlySavings, score, recommendations, highestTool } =
    useMemo(() => calculateAudit(tools), [tools]);

  // Add new tool row
  const addTool = () => {
    const newTool: ToolItem = {
      id: `tool-${Date.now()}`,
      name: "Claude",
      spend: 20,
      teamSize: 1,
    };
    setTools([...tools, newTool]);
  };

  // Remove a tool
  const removeTool = (id: string) => {
    if (tools.length <= 1) {
      setTools([{ id: `tool-${Date.now()}`, name: "ChatGPT", spend: 0, teamSize: 1 }]);
      return;
    }
    setTools(tools.filter((t) => t.id !== id));
  };

  // Update specific field in a tool
  const updateTool = (id: string, field: keyof ToolItem, value: any) => {
    setTools((prev) =>
      prev.map((t) => (t.id === id ? { ...t, [field]: value } : t))
    );
  };

  // Download simple text audit report
  const downloadReport = () => {
    const lines = [
      "==================================",
      "          SPENDIQ AUDIT REPORT    ",
      "==================================",
      `Date: ${new Date().toLocaleDateString()}`,
      "",
      `Active AI Tools:   ${tools.length}`,
      `Total Spend:       ${currency}${totalSpend} / month`,
      `Potential Savings: ${currency}${totalSavings} / month`,
      `Annual Savings:    ${currency}${yearlySavings} / year`,
      `Efficiency Score:  ${score} / 100`,
      "",
      "Tool Breakdown:",
      ...tools.map((t) => ` • ${t.name}: ${currency}${t.spend}/mo (${t.teamSize} user[s])`),
      "",
      "Recommendations:",
      ...recommendations.map(
        (r) => ` • [${r.toolName}]: ${r.suggestion} (Save ${currency}${r.savings}/mo)`
      ),
      "",
      "==================================",
      "Generated by SpendIQ Dashboard",
    ];

    const blob = new Blob([lines.join("\n")], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "spendiq-audit-report.txt";
    a.click();
    URL.revokeObjectURL(url);
  };

  const chartData = tools.map((t) => ({
    name: t.name,
    value: Number(t.spend) || 0,
  }));

  return (
    <div className="min-h-screen flex flex-col bg-transparent text-zinc-100">
      <Navbar />

      <main className="flex-1 max-w-5xl mx-auto w-full px-4 sm:px-6 py-8">
        
        {/* HEADER */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-6 border-b border-zinc-800">
          <div>
            <h1 className="text-2xl sm:text-3xl font-extrabold text-white">
              SpendIQ Dashboard
            </h1>
            <p className="text-xs sm:text-sm text-zinc-400 mt-1">
              Add your AI tools, see monthly costs, and find out where you can save.
            </p>
          </div>

          {/* CURRENCY SELECTOR */}
          <div className="flex items-center gap-2 self-start sm:self-auto">
            <label className="text-xs text-zinc-400 font-medium">Currency:</label>
            <select
              value={currency}
              onChange={(e) => setCurrency(e.target.value as Currency)}
              className="bg-zinc-900 border border-zinc-700 text-white text-xs font-semibold rounded-lg px-3 py-1.5 focus:outline-none focus:ring-1 focus:ring-indigo-500"
            >
              <option value="$">USD ($)</option>
              <option value="₹">INR (₹)</option>
              <option value="€">Euro (€)</option>
              <option value="£">Pound (£)</option>
            </select>
          </div>
        </div>

        {/* 4 STATS CARDS */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mt-6">
          
          <div className="bg-zinc-900/80 p-4 rounded-xl border border-zinc-800">
            <span className="text-xs text-zinc-400 block">Active Tools</span>
            <span className="text-2xl font-bold text-white mt-1 block">
              {tools.length}
            </span>
          </div>

          <div className="bg-zinc-900/80 p-4 rounded-xl border border-zinc-800">
            <span className="text-xs text-zinc-400 block">Total Spend</span>
            <span className="text-2xl font-bold text-red-400 mt-1 block">
              {currency}
              {totalSpend}
            </span>
            <span className="text-[11px] text-zinc-500">per month</span>
          </div>

          <div className="bg-zinc-900/80 p-4 rounded-xl border border-zinc-800">
            <span className="text-xs text-zinc-400 block">Monthly Savings</span>
            <span className="text-2xl font-bold text-emerald-400 mt-1 block">
              {currency}
              {totalSavings}
            </span>
            <span className="text-[11px] text-zinc-500">recoverable</span>
          </div>

          <div className="bg-zinc-900/80 p-4 rounded-xl border border-zinc-800">
            <span className="text-xs text-zinc-400 block">Annual Savings</span>
            <span className="text-2xl font-bold text-emerald-400 mt-1 block">
              {currency}
              {yearlySavings}
            </span>
            <span className="text-[11px] text-zinc-500">per year</span>
          </div>

        </div>

        {/* EFFICIENCY SCORE BAR */}
        <div className="mt-6 bg-zinc-900/70 p-4 rounded-xl border border-zinc-800 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div>
            <div className="flex items-center gap-2">
              <span className="text-xs text-zinc-400 font-semibold uppercase tracking-wider">
                AI Efficiency Score:
              </span>
              <span className={`text-sm font-extrabold ${score >= 80 ? "text-emerald-400" : score >= 60 ? "text-amber-400" : "text-red-400"}`}>
                {score}/100
              </span>
            </div>
            <p className="text-xs text-zinc-400 mt-0.5">
              {score >= 80
                ? "Your AI stack is lean and well-optimized."
                : score >= 60
                ? "You have moderate potential savings by adjusting plans."
                : "High waste detected. Look at the recommendations below."}
            </p>
          </div>

          <div className="w-full sm:w-48 bg-zinc-800 rounded-full h-2 overflow-hidden">
            <div
              className={`h-full rounded-full transition-all duration-300 ${
                score >= 80 ? "bg-emerald-400" : score >= 60 ? "bg-amber-400" : "bg-red-400"
              }`}
              style={{ width: `${score}%` }}
            />
          </div>
        </div>

        {/* TWO COLUMN SECTION */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 mt-6">
          
          {/* LEFT 2 COLS: TOOLS LIST */}
          <div className="lg:col-span-2 space-y-4">
            <div className="flex items-center justify-between">
              <h2 className="text-base font-bold text-white">Your Tools & Plans</h2>
              <button
                onClick={addTool}
                className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-semibold shadow transition"
              >
                <Plus className="w-3.5 h-3.5" />
                <span>Add Tool</span>
              </button>
            </div>

            <div className="space-y-3">
              {tools.map((item, index) => {
                const rec = recommendations.find((r) => r.toolId === item.id);

                return (
                  <div
                    key={item.id}
                    className="p-4 rounded-xl bg-zinc-900 border border-zinc-800 space-y-3"
                  >
                    <div className="flex items-center justify-between gap-3">
                      <div className="flex items-center gap-2 flex-1">
                        <span className="text-xs font-bold text-zinc-400">
                          #{index + 1}
                        </span>
                        <select
                          value={item.name}
                          onChange={(e) => updateTool(item.id, "name", e.target.value)}
                          className="bg-zinc-950 text-white text-xs font-semibold px-3 py-1.5 rounded-lg border border-zinc-700 focus:outline-none"
                        >
                          {POPULAR_TOOLS.map((toolName) => (
                            <option key={toolName} value={toolName}>
                              {toolName}
                            </option>
                          ))}
                        </select>
                      </div>

                      {tools.length > 1 && (
                        <button
                          onClick={() => removeTool(item.id)}
                          className="text-zinc-500 hover:text-red-400 p-1 text-xs transition"
                          title="Remove tool"
                        >
                          <Trash2 className="w-4 h-4" />
                        </button>
                      )}
                    </div>

                    <div className="grid grid-cols-2 gap-3">
                      <div>
                        <label className="text-[11px] text-zinc-400 block mb-1">
                          Monthly Spend ({currency})
                        </label>
                        <input
                          type="number"
                          min="0"
                          value={item.spend === 0 ? "" : item.spend}
                          onChange={(e) =>
                            updateTool(
                              item.id,
                              "spend",
                              e.target.value === "" ? 0 : Number(e.target.value)
                            )
                          }
                          placeholder="e.g. 20"
                          className="w-full bg-zinc-950 border border-zinc-700 rounded-lg px-3 py-1.5 text-xs text-white focus:outline-none"
                        />
                      </div>

                      <div>
                        <label className="text-[11px] text-zinc-400 block mb-1">
                          Team Size (Seats)
                        </label>
                        <input
                          type="number"
                          min="1"
                          value={item.teamSize === 0 ? "" : item.teamSize}
                          onChange={(e) =>
                            updateTool(
                              item.id,
                              "teamSize",
                              e.target.value === "" ? 1 : Number(e.target.value)
                            )
                          }
                          placeholder="1"
                          className="w-full bg-zinc-950 border border-zinc-700 rounded-lg px-3 py-1.5 text-xs text-white focus:outline-none"
                        />
                      </div>
                    </div>

                    {/* RECOMMENDATION PER TOOL */}
                    <div
                      className={`text-xs p-2.5 rounded-lg border flex items-start gap-2 ${
                        rec && rec.savings > 0
                          ? "bg-amber-950/20 border-amber-500/30 text-amber-200"
                          : "bg-zinc-950 border-zinc-800 text-zinc-400"
                      }`}
                    >
                      {rec && rec.savings > 0 ? (
                        <AlertCircle className="w-4 h-4 text-amber-400 flex-shrink-0 mt-0.5" />
                      ) : (
                        <CheckCircle className="w-4 h-4 text-emerald-400 flex-shrink-0 mt-0.5" />
                      )}
                      <div>
                        <p>{rec?.suggestion || "Optimized"}</p>
                        {rec && rec.savings > 0 && (
                          <p className="text-[11px] font-semibold text-emerald-400 mt-1">
                            Potential Savings: {currency}
                            {rec.savings}/month ({currency}
                            {rec.savings * 12}/year)
                          </p>
                        )}
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>

            <button
              onClick={addTool}
              className="w-full py-2.5 rounded-xl border border-dashed border-zinc-700 text-xs font-semibold text-zinc-300 hover:text-white hover:border-zinc-500 transition"
            >
              + Add Another Tool
            </button>
          </div>

          {/* RIGHT 1 COL: CHART & ACTIONS */}
          <div className="space-y-4">
            
            {/* SPENDING BREAKDOWN CHART */}
            <div className="bg-zinc-900/80 p-4 rounded-xl border border-zinc-800">
              <h3 className="text-xs font-bold text-white uppercase tracking-wider mb-2">
                Spending Breakdown
              </h3>
              <SpendingChart data={chartData} currency={currency} />
            </div>

            {/* HIGHEST SPENDING TOOL */}
            {highestTool && totalSpend > 0 && (
              <div className="bg-zinc-900/80 p-4 rounded-xl border border-zinc-800">
                <span className="text-xs text-zinc-400 block">Highest Cost Tool</span>
                <p className="text-lg font-bold text-white mt-1">{highestTool.name}</p>
                <p className="text-xs text-red-400 mt-0.5">
                  Current Spend: {currency}
                  {highestTool.spend}/month
                </p>
              </div>
            )}

            {/* AUDIT SUMMARY CARD */}
            <div className="bg-indigo-950/30 border border-indigo-500/30 p-4 rounded-xl text-xs space-y-2">
              <h4 className="font-bold text-indigo-300 flex items-center gap-1.5">
                <TrendingUp className="w-4 h-4" />
                Audit Summary
              </h4>
              <p className="text-zinc-300 leading-relaxed">
                You are currently tracking <strong className="text-white">{tools.length} AI tools</strong>.
                By following the recommendations, you could save approximately{" "}
                <strong className="text-emerald-400">
                  {currency}
                  {yearlySavings}
                </strong>{" "}
                every year!
              </p>
            </div>

            {/* DOWNLOAD REPORT BUTTON */}
            <button
              onClick={downloadReport}
              className="w-full inline-flex items-center justify-center gap-2 bg-emerald-600 hover:bg-emerald-500 text-white font-semibold text-xs py-3 rounded-xl shadow transition active:scale-95"
            >
              <Download className="w-4 h-4" />
              <span>Download Audit Report (.txt)</span>
            </button>

          </div>

        </div>

      </main>

      <Footer />
    </div>
  );
}